# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 407469dad7972a96cc93fd2b77599fa227e36ab0731b43c90f43a1d509719e4b56adc34a57a9d0bc37151054fa94e87ae6ba645f65eaaea4db7ad00f98a46314

test:
  secret_key_base: 1b6539ea9e1de14121de9e317c80a40bd32c75c68352a1758bfb9da31d8a9cc9f091c95b9cd652498f51e183b6ca2567d5fcb00c9aaa316bd1e7b21b31864c0c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
